language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  
before_commit:
  - pylint src
  - autopep8 --in-place --aggressive --aggressive src/DNN_one_layer.py
  - autopep8 --in-place --aggressive --aggressive src/GDNN_one_layer.py
  - autopep8 --in-place --aggressive --aggressive src/NN1.py


# command to run tests
script:
  - python src/GDNN_one_layer.py
